name: CI

on: [push, pull_request]

jobs:
    psalm:
        runs-on: ubuntu-latest

        steps:
            # Check out the repository under $GITHUB_WORKSPACE, so this job can access it
            - uses: actions/checkout@v2

            - name: Use PHP 7.4
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4

            - name: Install Composer dependencies
              run: composer install

            - name: Run tests
              run: vendor/bin/psalm

    phpunit:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: [7.3, 7.4]

        steps:
            # Check out the repository under $GITHUB_WORKSPACE, so this job can access it
            - uses: actions/checkout@v2

            - name: Use PHP ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Install Composer dependencies
              run: composer install

            - name: Run tests
              run: vendor/bin/phpunit
